### ISSUE TITLE
Just a comment about your example code, which people will copy

### ISSUE THREAD

**Issue by weberr13** [hydrogen18/stoppableListener#5]
When you increment the waitgroup you do so inside the go routine.  Since execution of go routines is not guaranteed to be in order this creates a race condition.  Simply do the `wg.Add(1)` *before* you create the listening go routine and you are safe.

**Comment by weberr13** [comment]
https://github.com/hydrogen18/stoppableListener/pull/6

**Comment by hydrogen18** [comment]
Merged
