### ISSUE TITLE
Close accepted client when stopping?

### ISSUE THREAD

**Issue by ksimka** [hydrogen18/stoppableListener#7]
``` go
newConn, err := sl.TCPListener.Accept()

//Check for the channel being closed
select {
case <-sl.stop:
    return nil, StoppedError
```

What if we're stopping, but a new client has been accepted? Wouldn't it be better to at least close it?

``` go
case <-sl.stop:
    if err == nil {
        newConn.Close()
    }
    return nil, StoppedError
```

Or it's useless?

**Comment by hydrogen18** [comment]
Technically speaking, you are correct. There is a race that could lead to the need for this.

**Comment by hydrogen18** [comment]
Would you like to open a pull request to address this concern?

**Comment by ksimka** [comment]
Done.
