### ISSUE TITLE
kills currently active connections

### ISSUE THREAD

**Issue by imoverclocked** [hydrogen18/stoppableListener#8]
If I run example (go 1.7.1) and I run: `while curl http://127.0.0.1:8080 ; do date; done` 

Then, I see:

```
Serving HTTP
^CGot signal:interrupt
Stopping listener
Waiting on server
```
(expected)

```
...
Hello HTTP!
Fri Oct 28 21:44:54 UTC 2016
Hello HTTP!
Fri Oct 28 21:44:54 UTC 2016
curl: (52) Empty reply from server
```

Which means the already accepted connection was interrupted mid-stream.

Looking into the bowels of net/http, it seems somewhat impossible because `go c.serve(ctx)` has no way of waiting on in-flight requests. There are a few issues open currently to try and fix this issue though:

https://github.com/golang/go/issues/4674
https://github.com/golang/go/issues/11219

The problem is that you can't just wait on http.Serve().

**Comment by imoverclocked** [comment]
https://github.com/tylerb/graceful does what you think it should... except that it takes a timeout.

**Comment by hydrogen18** [comment]
The intent of this package is stop the listening socket. The handling of any other sockets that have been opened as a result of that one is not in the scope of this package. I choose to solve this problem outside of the application layer, namely by using connection draining on a load balancer before issuing the stop command to my software.

Pull requests that add additional logic and tests to handle such cases are welcome.
